enyo.depends(
	"TorrentTableBodyCell.js",
	"TorrentTableHeadCell.js",
	"Torrent.js",
	"TorrentTableHead.js",
	"TorrentTable.js",
	"SelectFolderInput.js",
	"SmallLoading.js",
	"AddTorrentPref.js",
	"AddTorrentToolbarButton.js",
	"StartTorrentToolbarButton.js",
	"Toolbar.js",
	"PreferenceHolder.js",
	"App.js"
);