enyo.depends(
    "TrackerStats.js",
    "Tracker.js",
    "File.js",
    "FileStats.js",
	"Torrent.js",
	"TorrentsUpdater.js",
    "Units.js",
    "TransmissionSession.js",
	"TransmissionSessionUpdater.js"
);